FROM nginx:latest
RUN groupadd -r -g 1000 sufob && useradd -r -g sufob -u 1000 sufob
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./sites-available/sufob.dev.conf /etc/nginx/sites-available/sufob.dev.conf
COPY ./error_template /var/www/error_page
RUN mkdir -p /etc/nginx/sites-enabled && ln -s /etc/nginx/sites-available/sufob.dev.conf /etc/nginx/sites-enabled/ && rm /etc/nginx/conf.d/default.conf

