# Generated by Django 4.2.7 on 2023-12-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailusers', '0012_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SufobUsers',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailusers.userprofile')),
            ],
            bases=('wagtailusers.userprofile',),
        ),
    ]
