# Generated by Django 4.2.7 on 2023-12-03 04:54

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='md_content',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name='Markdown内容'),
        ),
    ]
