# Generated by Django 4.2.7 on 2023-12-14 14:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_md_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpageindex',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='简介'),
        ),
    ]
