# Generated by Django 4.2.11 on 2024-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_view_count_blogpageview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
