# Generated by Django 4.2.11 on 2024-04-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0005_alter_blogcategory_options_blogcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG'),
        ),
    ]
